############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://192.168.8.234:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 1993828xj
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 500000 #上传文件最大500KB
      max-request-size: 500000 #最大请求500KB

  redis:
    #host: 112.74.164.120
    password: 1993828xj
    database: 0
    sentinel:
      master: mymaster
      nodes:
        - 112.74.164.120:26379
        - 112.74.164.120:26380

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.food.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #sql语句打印建议在开发环境下使用，否则日志很冗余没有必要

#    map-underscore-to-camel-case: true
#    mapUnderscoreToCamelCase: true
#    auto-mapping-behavior: partial
############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql



logging:
  config: classpath:log4j2-pro.xml
